;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        haskell-indentation-common-electric-command
        yaml-electric-backspace
        yaml-electric-dash-and-dot
        ))

(setq mc/cmds-to-run-once
      '(
        ace-window
        beginning-of-buffer
        dap-tooltip-mouse-motion
        describe-symbol
        helm-find-files
        previous-buffer
        projectile-find-file
        ))
